### ISSUE TITLE
Obs not coming up on table view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-observations#11]
Look at patient "try" on walk-in (both list view and patient details)

**Comment by GabPoll** [comment]
i added point in the past and it appears fixed - coincidence? Closing for now.

**Comment by davidmiller** [comment]
I think it's probably #14 (Which I opened before I saw this :)

**Comment by michaeledwardmarks** [comment]
I'm reopening this as I have the same issue. Assume @davidmiller may well be correct about cause but helpful to have this open so we can check once #14 is fixed.

**Comment by michaeledwardmarks** [comment]
Fixed by #14
