### ISSUE TITLE
Y axes labels & numbers cut off on chart view

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-observations#12]

**Comment by davidmiller** [comment]
![obsgraph](https://cloud.githubusercontent.com/assets/17229/5690860/eff74b8c-989e-11e4-97d9-43236c405a68.png)

**Comment by michaeledwardmarks** [comment]
If we fix this then I think Obs chart is ready to go.

**Comment by michaeledwardmarks** [comment]
Fixed

**Comment by GabPoll** [comment]
Is this deployed to elcid-opat? If so, this isn't fixed as it only displays 2 digits on the axis (more than before). 3rd one still cut off.
![pulse axis](https://cloud.githubusercontent.com/assets/4605661/5887354/0c4242a8-a388-11e4-958c-fdba0b26e220.png)

**Comment by michaeledwardmarks** [comment]
elcid-search

**Comment by GabPoll** [comment]
ah ok - agree fixed. How was i supposed to know where the fix had been deployed to BTW?

**Comment by michaeledwardmarks** [comment]
I believe that we have moved back to elCID-Search which == elCID-Live
