### ISSUE TITLE
X axis on charts should plot points by time (minutes?) over 24 hour period, not by day

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-observations#13]
For patient "try" i entered 2 sets of obs 2 mins apart, and it plotted them as the same point on x-axis as it was the same day

**Comment by davidmiller** [comment]
Yep - we need to combine date & time to make a full timestamp.

**Comment by davidmiller** [comment]
Deployed to elcid-search !

**Comment by michaeledwardmarks** [comment]
Fixed

**Comment by GabPoll** [comment]
nice
