### ISSUE TITLE
Make ADD Obs Action button be in the sidebar for relevant patients

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-observations#18]
Have we considered this.

Just one button.
On opening the chart/table there could be an option to record new set of obs prompting the observation modal.

Reduces the number of buttons needed on screen.

**Comment by GabPoll** [comment]
good idea.

**Comment by davidmiller** [comment]
I don't really think there was ever a good reason to have the table/chart in a modal on the detail view ! :) 

- [ ] Display table/chart on the details page w/out a modal
- [ ] Add obs on detail in modal
- [ ] List view display last obs record
- [ ] List view button to add new obs
- [ ] List view button to view obs chart

**Comment by michaeledwardmarks** [comment]
Agree but if displaying on detail view then suggest use integrated summary obs chart #8

**Comment by GabPoll** [comment]
@davidmiller might just be worth checking that someone wants it on list view. Walk in perhaps? Otherwise may not be worth the effort of setting it up that way.

**Comment by michaeledwardmarks** [comment]
List view obs definitely wanted in walk in.

**Comment by michaeledwardmarks** [comment]
There needs to be an action button in the new sidebar for ADD observation - on list view for both OPAT and Walk-In patients.

**Comment by davidmiller** [comment]
Given that we now have full obs from list view I think this is done for now !
