### ISSUE TITLE
Date and time should autoset for obs on list view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-observations#19]
This happens for patient detail view but not list view
Unclear if this is linked/separate from #10

**Comment by GabPoll** [comment]
where are obs used in list view? walk-in?

**Comment by michaeledwardmarks** [comment]
Walk-In

**Comment by davidmiller** [comment]
Date & time now autoset on list view elcid04-tes

**Comment by michaeledwardmarks** [comment]
Closed
