### ISSUE TITLE
Obs entered on patient detail view not showing up when Obs opened on List view

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-observations#21]
Unclear if this is the same as #10 

See bob on walk-in nurse list on elcid-search.
Look  on detail view.
Set of obs saved
show up on chart
Go back to bob on list view
open chart - no saved obs

TypeError: Cannot read property 'observation' of undefined
    at $scope.render_charts (http://elcid-search.herokuapp.com/assets/js/obs/controllers/obs_chart.6c285cda05ea.js:45:33)
    at http://elcid-search.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:14211:28
    at completeOutstandingRequest (http://elcid-search.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:4349:10)
    at http://elcid-search.herokuapp.com/assets/js/angular-1.2.20/angular.28f401490ec3.js:4650:7

**Comment by davidmiller** [comment]
I can't reproduce this at all :(

Unless you can reproduce it with a new patient/set of obs I move to close !

**Comment by michaeledwardmarks** [comment]
Note timezone thing but otherwise not an issue.
Closing.
