### ISSUE TITLE
Observation needs to record time

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-observations#4]

**Comment by davidmiller** [comment]
This is no longer an issue for me on e.g. elcid-opat @gabpoll?

**Comment by GabPoll** [comment]
the buttons for going up and down hours & minutes don't work for me when looking on single patient view.

**Comment by davidmiller** [comment]
Deployed to elcid-search !

**Comment by michaeledwardmarks** [comment]
Fixed

**Comment by GabPoll** [comment]
@davidmiller is this on elcid-opat? If so, the minute scrolling buttons still don't work when they first pop up.

**Comment by GabPoll** [comment]
ignore previous comment - on elcid-search. I see it & fixed.
